### PR TITLE
Wedding rsvp off platform project

### PR DESCRIPTION
**Pull request by Quentoya**
Elizabeth and Philip are delighted that you are planning on coming to their wedding! 
Before submitting this PR, please make sure:

- [ ] Your name is added to the list of guests with proper spelling.
- [ ] You have added the correct number of guests that are coming with and including you.
- [ ] The format of the markdown table in the `guests.md` file is valid.

### CODE REVIEW

**Comment by Quentoya** [comment]
Add my name to guest list

**Comment by rstanton91** [comment]
added my guests

**Comment by MartaKutash** [comment]
Added my name

**Comment by B-Chiu** [comment]
How come I am getting a 
"remote: Permission to Codecademy...git denied to B-Chiu"?
"fatal: unable to access 'https://github.com/Codecademy/wedding..git/'" The requested URL returned error: 403

**Comment by patryk77k** [comment]
Added my name to the list of guests.

**Comment by Mersand5** [comment]
added my name to the guest list

**Comment by ctrl-jr** [comment]
added my name to the guest list!

**Comment by Tushartk22** [comment]
added my name to the guest list

**Comment by naveengatlewar** [comment]
Added my name

**Comment by lauren-m-johnson** [comment]
Added my name to the guest list

**Comment by H-Simpkins** [comment]
Added my name to the guest list

**Comment by AnotherBrowncoat** [comment]
Added my name the list of guests

**Comment by Kata10** [comment]
Added my name to the guest list

**Comment by OmarCCh** [comment]
Hi! Added my name to the guest list!

**Comment by dharshinidha** [comment]
Added my name to the guest list

**Comment by Knegewo** [comment]
RVSP

**Comment by LolaSL** [comment]
Added my name to the guest list

**Comment by FlowersxEggesddrropssoups** [comment]
**Added my name to the guest list**

**Elizabeth & Philip**
Elizabeth and Philip are inviting everyone to their wedding! They would like all the guests to RSVP to their wedding by adding their names to the list of the guests in this repository.

Let Elizabeth and Philip know if you can make it to their wedding by following the instructions!

How to RSVP
Assumptions
You are currently signed into your GitHub account
You have basic familiarity with Markdown
You have Git command line tool installed on your computer, and it is set up to access your Github account
Instructions
Start

**Comment by Orionsquare** [comment]
Add name to guestlist

**Comment by Knegewo** [comment]
None

**Comment by jayaadityathota** [comment]
Added my name to the list of guests

**Comment by HyerimKim0104** [comment]
added my name

**Comment by Patchalv** [comment]
Added my name

**Comment by shanetgit** [comment]
added my name

**Comment by hanlizke** [comment]
Added my name to the guest list

**Comment by AlexandraMasson** [comment]
Added my name to the guest list under Alexandra Jusino

**Comment by sanjeevanlikestocode** [comment]
added my list to guest list

**Comment by Yusif99** [comment]
added name

**Comment by anh0uan42** [comment]
added my name to the guess list

**Comment by vladiK178** [comment]
added my name to the guess list

**Comment by DanielAsare-ux** [comment]
Added my name

**Comment by ChalkyVaati** [comment]
Added my name

**Comment by kebrcic** [comment]
added my name

**Comment by alextristrammoore1** [comment]
added my name

**Comment by DizzyWizzy88** [comment]
Added my name to the guest list.

**Comment by AlphaPersei** [comment]
Added my name to the list of guests.

**Comment by SpikeyMikie** [comment]
Added my name to the list of guests.

**Pull request closed without merging**
